# -*- coding: utf-8 -*-
"""Finetuned_CPDP_FINAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XepJEy6A3DNnEpFffazKPWQJF5_A1pgW
"""

from google.colab import drive
drive.mount('/content/drive')

#torch.cuda.empty_cache()

"""#confug.py"""

import os
import sys
import time
import torch
import random
import logging
import argparse
from datetime import datetime
import pandas as pd

import logging

####### remainin ###########

####### saved ########
'''
'ant_1.5-1.6'       'ant_1.6-1.7'
'camel_1.2-1.4'     'camel_1.4-1.6'
'poi_1.5-2.5'       'poi_2.5-3.0'
'jedit_3.2-4.0'     'jedit_4.0-4.1'
'lucene_2.0-2.2'    'lucene_2.2-2.4'
'synapse_1.0-1.1'   'synapse_1.1-1.2'
'ivy_1.4-2.0'       'log4j_1.0-1.1'
'xalan_2.4-2.5'     'xerces_1.2-1.3'
'velocity'
'''

'''
project_list = ['ant_1.7',
'camel_1.6',
'ivy_2.0',
'jedit_4.2',
'log4j_1.1',
'lucene_2.4',
'poi_3.0',
'synapse_1.2',
'velocity_1.6',
'xalan_2.5',
'xerces_1.4.4']

'''

torch.cuda.empty_cache()

import logging
'''num_classes = {'ant_camel': 2,'ant_1.5-1.6': 2, 'ant_1.6-1.7': 2,'camel_1.2-1.4': 2,
'camel_1.4-1.6': 2,'ivy_1.4-2.0': 2, 'jedit_3.2-4.0': 2,'jedit_4.0-4.1': 2,
'log4j_1.0-1.1': 2,'lucene_2.0-2.2': 2, 'lucene_2.2-2.4': 2,'poi_1.5-2.5': 2,
'poi_2.5-3.0': 2,'synapse_1.0-1.1': 2, 'synapse_1.1-1.2': 2,'xalan_2.4-2.5': 2,
'xerces_1.2-1.3': 2}'''
''' Base '''
#data_dir='/content/drive/MyDrive/DualConSDP_72_Percent/data_SDP'
#data_dir='/content/drive/MyDrive/Prectice_Project/DualConSDP_72_Percent/data_SDP'
data_dir='/content/drive/MyDrive/All_Data/AST_Tokens/sequence_and_label'



train_dataset = 'xerces_1.4.4'
test_dataset = 'xalan_2.5'

dataset_name = train_dataset+'_'+test_dataset

model_name='roberta' # choices=['bert', 'roberta','microsoft/codebert-base'])
method='scl' # choices=['ce', 'scl', 'dualcl'])

''' Optimization '''
train_batch_size=1
test_batch_size=32
lr=1e-5
decay=0.01
alpha=0.5
temp=0.1
''' Environment '''
backend=False
timestamp='{:.0f}{:03}'.format(time.time(), random.randint(0, 999))
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu') # ='cuda' if torch.cuda.is_available() else 'cpu')
num_classes = 2 #num_classes[args.dataset]

#to be decided #######
log_dir = '/content/drive/MyDrive/Proposed_BaseLine/CPDP_CL/finetune/log'
log_name = '/content/drive/MyDrive/Proposed_BaseLine/CPDP_CL/finetune/log/{}_{}_{}_{}.log'.format(dataset_name, model_name, method, datetime.now().strftime('%Y-%m-%d_%H-%M-%S')[2:])

if not os.path.exists(log_dir):
  os.mkdir(log_dir)


logger = logging.getLogger()
logger.setLevel(logging.INFO)
logger.addHandler(logging.StreamHandler(sys.stdout))
logger.addHandler(logging.FileHandler(os.path.join('logs', log_name)))

#/content/drive/MyDrive/Proposed_BaseLine/proposed_model/Results_WP_CP/
'''
if not os.path.exists(log_name):
  os.mkdir(log_name)
'''

"""#preprocess HC dataset"""

'''promise_dim_train = 23
promise_dim_test = 19'''

promise_dim = 19

from sklearn.preprocessing import StandardScaler
def pre_process(X_data):
  sc = StandardScaler()
  X_data =  X_data.split(',')
  X_data =X_data[0:promise_dim]
  X_data = [[float(x)] for x in X_data]
  #X_data = [float(x) for x in X_data]
  sc.fit(X_data)
  X_data=sc.transform(X_data)
  X_data = [x[0] for x in X_data]
  #print(X_data)
  return X_data

"""# Util_data"""

import os
import json
import torch
import random
from functools import partial
from torch.utils.data import Dataset, DataLoader

import re

class MyDataset(Dataset):

    def __init__(self, raw_data, label_dict, tokenizer, model_name, method):

        #label_list = list(label_dict.keys()) if method not in ['ce'] else []
        sep_token = ['[SEP]'] if model_name == 'bert' else ['</s>']
        dataset = list()

        for data in raw_data:

          regex='(\S*)[_]'
          data['sequence']= data['sequence'].lower()
          tokens = re.findall(regex, data['sequence'])

          #data['sequence'] = data['sequence'].replace("_", " ")
          #tokens = data['sequence'].lower().split(' ')
          label_id = label_dict[data['bug']]
          prom_data = data['promise']
          prom_data = pre_process(prom_data)
          dataset.append((sep_token + tokens, prom_data, label_id))

        self._dataset = dataset

    def __getitem__(self, index):
        return self._dataset[index]

    def __len__(self):
        return len(self._dataset)


def my_collate(batch, tokenizer, method, num_classes):
    tokens,promise_data, label_ids = map(list, zip(*batch))
    text_ids = tokenizer(tokens,
                         padding=True,
                         truncation=True,
                         max_length=512,
                         is_split_into_words=True,
                         add_special_tokens=True,
                         return_tensors='pt')
    '''if method not in ['ce', 'scl','dualcl']:
        positions = torch.zeros_like(text_ids['input_ids'])
        positions[:, num_classes:] = torch.arange(0, text_ids['input_ids'].size(1)-num_classes)
        text_ids['position_ids'] = positions'''
    return text_ids,promise_data, torch.tensor(label_ids)

from torch.utils.data import WeightedRandomSampler
def weight_sampler(trainset):
  count_true=0
  count_neg=0
  for i in range(len(trainset)):
    if trainset[i][2]==0:
      count_true += 1
    else:
      count_neg +=1
  #print(count_true,count_neg)
  counts=[count_true,count_neg]
  class_weights=[sum(counts)/c for c in counts]
  class_weights_all = [] #torch.tensor(len(trainset))
  for i in range(len(trainset)):
    if trainset[i][2]==0:
      class_weights_all.append(class_weights[0])
    else:
      class_weights_all.append(class_weights[1])
  target_tensor = torch.Tensor(class_weights_all)
  weighted_sampler = WeightedRandomSampler(
    weights=class_weights_all,
    num_samples=len(class_weights_all),
    replacement=True)

  return weighted_sampler

def load_data(train_dataset,test_dataset, data_dir, tokenizer, train_batch_size, test_batch_size, model_name, method, workers):

    train_project=train_dataset.split("_")[0]
    train_version = train_dataset.split("_")[1]

    test_project=test_dataset.split("_")[0]
    test_version = test_dataset.split("_")[1]

    Project_Train= train_project +'_'+ train_version+'.json'
    Project_Test = test_project + '_'+ test_version +'.json'

    train_data = json.load(open(os.path.join(data_dir,Project_Train ), 'r', encoding='utf-8'))
    print("train")
    test_data = json.load(open(os.path.join(data_dir, Project_Test), 'r', encoding='utf-8'))
    print("test")
    label_dict = {'positive': 0, 'negative': 1}


    trainset = MyDataset(train_data, label_dict, tokenizer, model_name, method)
    testset = MyDataset(test_data, label_dict, tokenizer, model_name, method)

    #testset, validset = train_test_split(testset, test_size=0.2, random_state=4)

    weighted_sampler=weight_sampler(trainset)

    train_dataloader = DataLoader(trainset, train_batch_size, shuffle=False, num_workers=workers,
                                  collate_fn=partial(my_collate, tokenizer=tokenizer,method='dualcl', num_classes=2),sampler=weighted_sampler, pin_memory=True)
    #valid_dataloader = DataLoader(validset, test_batch_size, shuffle=False, num_workers=workers,
    #                             collate_fn=partial(my_collate, tokenizer=tokenizer,method='dualcl', num_classes=2), pin_memory=True)
    test_dataloader = DataLoader(testset, test_batch_size, shuffle=False, num_workers=workers,
                                 collate_fn=partial(my_collate, tokenizer=tokenizer,method='dualcl', num_classes=2), pin_memory=True)

    return train_dataloader, test_dataloader   #, valid_dataloader

'''
train_dataloader, test_dataloader = load_data(train_dataset,test_dataset, data_dir, tokenizer, train_batch_size, test_batch_size, model_name, method, 2)

a=[]
for inputs, promise, targets in tqdm(test_dataloader, disable=backend, ascii=' >='):
  a.append((inputs, promise, targets))

np.array(a[0][1]).shape, np.array(a[0][0]).shape, np.array(a[0][2]).shape
'''

"""#loss function"""

import torch
import torch.nn as nn
import torch.nn.functional as F

class CELoss(nn.Module):

    def __init__(self):
        super().__init__()
        self.xent_loss = nn.CrossEntropyLoss(torch.Tensor([0.75, 0.44]))

    def forward(self, outputs, targets):
        return self.xent_loss(outputs['predicts'], targets)

class SupConLoss(nn.Module):

    def __init__(self, alpha, temp):
        super().__init__()
        self.xent_loss = nn.CrossEntropyLoss()
        self.alpha = alpha
        self.temp = temp

    def nt_xent_loss(self, anchor, target, labels):
        with torch.no_grad():
            labels = labels.unsqueeze(-1)
            mask = torch.eq(labels, labels.transpose(0, 1))
            # delete diag elem
            mask = mask ^ torch.diag_embed(torch.diag(mask))
        # compute logits
        anchor_dot_target = torch.einsum('bd,cd->bc', anchor, target) / self.temp
        # delete diag elem
        anchor_dot_target = anchor_dot_target - torch.diag_embed(torch.diag(anchor_dot_target))
        # for numerical stability
        logits_max, _ = torch.max(anchor_dot_target, dim=1, keepdim=True)
        logits = anchor_dot_target - logits_max.detach()
        # compute log prob
        exp_logits = torch.exp(logits)
        # mask out positives
        logits = logits * mask
        log_prob = logits - torch.log(exp_logits.sum(dim=1, keepdim=True) + 1e-12)
        # in case that mask.sum(1) is zero
        mask_sum = mask.sum(dim=1)
        mask_sum = torch.where(mask_sum == 0, torch.ones_like(mask_sum), mask_sum)
        # compute log-likelihood
        pos_logits = (mask * log_prob).sum(dim=1) / mask_sum.detach()
        loss = -1 * pos_logits.mean()
        return loss

    def forward(self, outputs, targets):
        normed_cls_feats = F.normalize(outputs['cls_feats'], dim=-1)
        ce_loss = (1 - self.alpha) * self.xent_loss(outputs['predicts'], targets)
        cl_loss = self.alpha * self.nt_xent_loss(normed_cls_feats, normed_cls_feats, targets)
        return ce_loss + cl_loss

class DualLoss(SupConLoss):

    def __init__(self, alpha, temp):
        super().__init__(alpha, temp)

    def forward(self, outputs, targets):
        normed_cls_feats = F.normalize(outputs['cls_feats'], dim=-1)
        normed_label_feats = F.normalize(outputs['label_feats'], dim=-1)
        normed_pos_label_feats = torch.gather(normed_label_feats, dim=1, index=targets.reshape(-1, 1, 1).expand(-1, 1, normed_label_feats.size(-1))).squeeze(1)
        ce_loss = (1 - self.alpha) * self.xent_loss(outputs['predicts'], targets)
        cl_loss_1 = 0.5 * self.alpha * self.nt_xent_loss(normed_pos_label_feats, normed_cls_feats, targets)
        cl_loss_2 = 0.5 * self.alpha * self.nt_xent_loss(normed_cls_feats, normed_pos_label_feats, targets)
        return ce_loss + cl_loss_1 + cl_loss_2

#!/usr/bin/env python
# encoding: utf-8


import torch

min_var_est = 1e-8


def mmd_loss(x_src, x_tar, gamma):

    if gamma is None:
        gamma = 5

    # return mmd_linear(x_src, x_tar)
    return mix_rbf_mmd2(x_src, x_tar, [gamma])


def multi_mmd_loss(x_src, x_tar, kernel_mul=2.0, kernel_num=5, fix_sigma=None):
    gamma = get_multi_sigma(x_src, x_tar, kernel_mul, kernel_num, fix_sigma)
    return mix_rbf_mmd2(x_src, x_tar, gamma)


def dan_loss(x_src, x_tar, kernel_mul=2.0, kernel_num=5, fix_sigma=None, biased=True):
    return mix_dan_rbf_mmd2(x_src, x_tar, kernel_mul, kernel_num, fix_sigma, biased)


# def my_mmd_linear(f_of_X, f_of_Y):
#     loss = torch.mean(torch.mm(f_of_X, torch.transpose(f_of_Y, 0, 1)))
#     return loss

def mmd_linear(f_of_X, f_of_Y):
    delta = f_of_X - f_of_Y
    loss = torch.mean(torch.mm(delta, torch.transpose(delta, 0, 1)))
    return loss

# Consider linear time MMD with a linear kernel:
# K(f(x), f(y)) = f(x)^Tf(y)
# h(z_i, z_j) = k(x_i, x_j) + k(y_i, y_j) - k(x_i, y_j) - k(x_j, y_i)
#             = [f(x_i) - f(y_i)]^T[f(x_j) - f(y_j)]
#
# f_of_X: batch_size * k
# f_of_Y: batch_size * k
def linear_mmd2(f_of_X, f_of_Y):
    loss = 0.0
    delta = f_of_X - f_of_Y
    #loss = torch.mean((delta[:-1] * delta[1:]).sum(1))
    loss = torch.mean(torch.mm(delta, torch.transpose(delta, 0, 1)))
    #delta = f_of_X - f_of_Y
    #loss = torch.mean((delta * delta).sum(1))
    #print(loss)
    return loss


# Consider linear time MMD with a polynomial kernel:
# K(f(x), f(y)) = (alpha*f(x)^Tf(y) + c)^d
# f_of_X: batch_size * k
# f_of_Y: batch_size * k
def poly_mmd2(f_of_X, f_of_Y, d=1, alpha=1.0, c=2.0):
    K_XX = (alpha * (f_of_X[:-1] * f_of_X[1:]).sum(1) + c)
    #print(K_XX)
    K_XX_mean = torch.mean(K_XX.pow(d))

    K_YY = (alpha * (f_of_Y[:-1] * f_of_Y[1:]).sum(1) + c)
    K_YY_mean = torch.mean(K_YY.pow(d))

    K_XY = (alpha * (f_of_X[:-1] * f_of_Y[1:]).sum(1) + c)
    K_XY_mean = torch.mean(K_XY.pow(d))

    K_YX = (alpha * (f_of_Y[:-1] * f_of_X[1:]).sum(1) + c)
    K_YX_mean = torch.mean(K_YX.pow(d))
    #print(K_XX_mean + K_YY_mean - K_XY_mean - K_YX_mean)
    return K_XX_mean + K_YY_mean - K_XY_mean - K_YX_mean


def _mix_rbf_kernel(X, Y, sigma_list):
    # assert(X.size(0) == Y.size(0))
    m = X.size(0)
    n = Y.size(0)

    Z = torch.cat((X, Y), 0)
    ZZT = torch.mm(Z, Z.t())
    diag_ZZT = torch.diag(ZZT).unsqueeze(1)
    Z_norm_sqr = diag_ZZT.expand_as(ZZT)
    exponent = Z_norm_sqr - 2 * ZZT + Z_norm_sqr.t()

    K = 0.0
    for sigma in sigma_list:
        gamma = 1.0 / (2 * sigma**2)
        K += torch.exp(-gamma * exponent)

    return K[:m, :m], K[:m, m:m+n], K[m:, m:m+n], len(sigma_list)


def mix_rbf_mmd2(X, Y, sigma_list, biased=True):
    K_XX, K_XY, K_YY, d = _mix_rbf_kernel(X, Y, sigma_list)
    # return _mmd2(K_XX, K_XY, K_YY, const_diagonal=d, biased=biased)
    return _mmd2(K_XX, K_XY, K_YY, const_diagonal=False, biased=biased)


def mix_rbf_mmd2_and_ratio(X, Y, sigma_list, biased=True):
    K_XX, K_XY, K_YY, d = _mix_rbf_kernel(X, Y, sigma_list)
    # return _mmd2_and_ratio(K_XX, K_XY, K_YY, const_diagonal=d, biased=biased)
    return _mmd2_and_ratio(K_XX, K_XY, K_YY, const_diagonal=False, biased=biased)


def mix_dan_rbf_mmd2(X, Y, kernel_mul=2.0, kernel_num=5, fix_sigma=None, biased=True):

    K = multi_guassian_kernel(X, Y, kernel_mul=kernel_mul, kernel_num=kernel_num, fix_sigma=fix_sigma)

    m = X.size(0)
    n = Y.size(0)
    K_XX = K[:m, :m]
    K_XY = K[:m, m:m + n]
    K_YY = K[m:, m:m + n]

    return _mmd2(K_XX, K_XY, K_YY, const_diagonal=False, biased=biased)


################################################################################
# Helper functions to compute variances based on kernel matrices
################################################################################

def get_multi_sigma(source, target, kernel_mul=2.0, kernel_num=5, fix_sigma=None):
    n_samples = int(source.size()[0]) + int(target.size()[0])
    total = torch.cat([source, target], dim=0)
    total0 = total.unsqueeze(0).expand(int(total.size(0)), int(total.size(0)), int(total.size(1)))
    total1 = total.unsqueeze(1).expand(int(total.size(0)), int(total.size(0)), int(total.size(1)))
    L2_distance = ((total0 - total1) ** 2).sum(2)
    if fix_sigma:
        bandwidth = fix_sigma
    else:
        bandwidth = torch.sum(L2_distance.data) / (n_samples ** 2 - n_samples)
    bandwidth /= kernel_mul ** (kernel_num // 2)
    bandwidth_list = [bandwidth * (kernel_mul ** i) for i in range(kernel_num)]

    return bandwidth_list

def multi_guassian_kernel(source, target, kernel_mul=2.0, kernel_num=5, fix_sigma=None):
    n_samples = int(source.size()[0]) + int(target.size()[0])
    total = torch.cat([source, target], dim=0)
    total0 = total.unsqueeze(0).expand(int(total.size(0)), int(total.size(0)), int(total.size(1)))
    total1 = total.unsqueeze(1).expand(int(total.size(0)), int(total.size(0)), int(total.size(1)))
    L2_distance = ((total0 - total1) ** 2).sum(2)
    if fix_sigma:
        bandwidth = fix_sigma
    else:
        bandwidth = torch.sum(L2_distance.data) / (n_samples ** 2 - n_samples)
    bandwidth /= kernel_mul ** (kernel_num // 2)
    bandwidth_list = [bandwidth * (kernel_mul ** i) for i in range(kernel_num)]
    kernel_val = [torch.exp(-L2_distance / bandwidth_temp) for bandwidth_temp in bandwidth_list]
    return sum(kernel_val)  # /len(kernel_val)


def _mmd2(K_XX, K_XY, K_YY, const_diagonal=False, biased=False):
    m = K_XX.size(0)
    n = K_YY.size(0)

    # Get the various sums of kernels that we'll use
    # Kts drop the diagonal, but we don't need to compute them explicitly
    if const_diagonal is not False:
        diag_X = diag_Y = const_diagonal
        sum_diag_X = m * const_diagonal
        sum_diag_Y = n * const_diagonal
    else:
        diag_X = torch.diag(K_XX)                       # (m,)
        diag_Y = torch.diag(K_YY)                       # (m,)
        sum_diag_X = torch.sum(diag_X)
        sum_diag_Y = torch.sum(diag_Y)

    Kt_XX_sums = K_XX.sum(dim=1) - diag_X             # \tilde{K}_XX * e = K_XX * e - diag_X
    Kt_YY_sums = K_YY.sum(dim=1) - diag_Y             # \tilde{K}_YY * e = K_YY * e - diag_Y
    K_XY_sums_0 = K_XY.sum(dim=0)                     # K_{XY}^T * e

    Kt_XX_sum = Kt_XX_sums.sum()                       # e^T * \tilde{K}_XX * e
    Kt_YY_sum = Kt_YY_sums.sum()                       # e^T * \tilde{K}_YY * e
    K_XY_sum = K_XY_sums_0.sum()                       # e^T * K_{XY} * e

    if biased:
        mmd2 = ((Kt_XX_sum + sum_diag_X) / (m * m)
            + (Kt_YY_sum + sum_diag_Y) / (n * n)
            - 2.0 * K_XY_sum / (m * n))
    else:
        mmd2 = (Kt_XX_sum / (m * (m - 1))
            + Kt_YY_sum / (n * (n - 1))
            - 2.0 * K_XY_sum / (m * n))

    return mmd2


def _mmd2_and_ratio(K_XX, K_XY, K_YY, const_diagonal=False, biased=False):
    mmd2, var_est = _mmd2_and_variance(K_XX, K_XY, K_YY, const_diagonal=const_diagonal, biased=biased)
    loss = mmd2 / torch.sqrt(torch.clamp(var_est, min=min_var_est))
    return loss, mmd2, var_est


def _mmd2_and_variance(K_XX, K_XY, K_YY, const_diagonal=False, biased=False):
    m = K_XX.size(0)    # assume X, Y are same shape

    # Get the various sums of kernels that we'll use
    # Kts drop the diagonal, but we don't need to compute them explicitly
    if const_diagonal is not False:
        diag_X = diag_Y = const_diagonal
        sum_diag_X = sum_diag_Y = m * const_diagonal
        sum_diag2_X = sum_diag2_Y = m * const_diagonal**2
    else:
        diag_X = torch.diag(K_XX)                       # (m,)
        diag_Y = torch.diag(K_YY)                       # (m,)
        sum_diag_X = torch.sum(diag_X)
        sum_diag_Y = torch.sum(diag_Y)
        sum_diag2_X = diag_X.dot(diag_X)
        sum_diag2_Y = diag_Y.dot(diag_Y)

    Kt_XX_sums = K_XX.sum(dim=1) - diag_X             # \tilde{K}_XX * e = K_XX * e - diag_X
    Kt_YY_sums = K_YY.sum(dim=1) - diag_Y             # \tilde{K}_YY * e = K_YY * e - diag_Y
    K_XY_sums_0 = K_XY.sum(dim=0)                     # K_{XY}^T * e
    K_XY_sums_1 = K_XY.sum(dim=1)                     # K_{XY} * e

    Kt_XX_sum = Kt_XX_sums.sum()                       # e^T * \tilde{K}_XX * e
    Kt_YY_sum = Kt_YY_sums.sum()                       # e^T * \tilde{K}_YY * e
    K_XY_sum = K_XY_sums_0.sum()                       # e^T * K_{XY} * e

    Kt_XX_2_sum = (K_XX ** 2).sum() - sum_diag2_X      # \| \tilde{K}_XX \|_F^2
    Kt_YY_2_sum = (K_YY ** 2).sum() - sum_diag2_Y      # \| \tilde{K}_YY \|_F^2
    K_XY_2_sum  = (K_XY ** 2).sum()                    # \| K_{XY} \|_F^2

    if biased:
        mmd2 = ((Kt_XX_sum + sum_diag_X) / (m * m)
            + (Kt_YY_sum + sum_diag_Y) / (m * m)
            - 2.0 * K_XY_sum / (m * m))
    else:
        mmd2 = (Kt_XX_sum / (m * (m - 1))
            + Kt_YY_sum / (m * (m - 1))
            - 2.0 * K_XY_sum / (m * m))

    var_est = (
        2.0 / (m**2 * (m - 1.0)**2) * (2 * Kt_XX_sums.dot(Kt_XX_sums) - Kt_XX_2_sum + 2 * Kt_YY_sums.dot(Kt_YY_sums) - Kt_YY_2_sum)
        - (4.0*m - 6.0) / (m**3 * (m - 1.0)**3) * (Kt_XX_sum**2 + Kt_YY_sum**2)
        + 4.0*(m - 2.0) / (m**3 * (m - 1.0)**2) * (K_XY_sums_1.dot(K_XY_sums_1) + K_XY_sums_0.dot(K_XY_sums_0))
        - 4.0*(m - 3.0) / (m**3 * (m - 1.0)**2) * (K_XY_2_sum) - (8 * m - 12) / (m**5 * (m - 1)) * K_XY_sum**2
        + 8.0 / (m**3 * (m - 1.0)) * (
            1.0 / m * (Kt_XX_sum + Kt_YY_sum) * K_XY_sum
            - Kt_XX_sums.dot(K_XY_sums_1)
            - Kt_YY_sums.dot(K_XY_sums_0))
        )
    return mmd2, var_est

gamma = -6e-4
beta = 3e2
def mmd_loss_2(x_s1,x_s2):
        x_ss=torch.exp(torch.pow((x_s1-x_s2),2).sum()* gamma)
        x_tt=torch.exp(torch.pow((x_s2-x_s1),2).sum()* gamma)
        #x_s1t2=torch.exp(torch.pow((x_s1-x_t2),2).sum()*self.gamma)
        #x_s2t1=torch.exp(torch.pow((x_s2-x_t1),2).sum()*self.gamma)
        mmd_dis=( x_ss + x_tt )
        return mmd_dis

"""#model"""

import torch
import torch.nn as nn

'''class Transformer(nn.Module):

    def __init__(self, base_model, num_classes, method, promise_dim):
        super().__init__()
        self.base_model = base_model
        self.num_classes = 1 #num_classes
        self.method = method
        #self.l2_lambda = 0.001
        #self.l2_regularization = torch.tensor(0., requires_grad=True)
        self.linear = nn.Linear(base_model.config.hidden_size, 300)
        self.pred_class = nn.Linear(300+promise_dim, num_classes)
        self.dropout = nn.Dropout(0.5)
        for param in base_model.parameters():
            param.requires_grad_(True)

    def forward(self,promise, *args, **kwargs):
        raw_outputs = self.base_model(*args, **kwargs)
        hiddens = raw_outputs.last_hidden_state

        #cls_feats = torch.sum(hiddens, 1)  sum of all hidden
        cls_feats = torch.mean(hiddens, 1)  #average of all hidden

        #cls_feats = hiddens[:, 0, :]

        # take average of each layer means merge ---------  done
        # LR Layer ---done --
        # merge HC  ----

        label_feats = None
        predicts = self.linear(self.dropout(cls_feats))
        predicts = torch.cat((predicts, promise), 1)
        predicts = self.pred_class(self.dropout(predicts))
        predicts = torch.sigmoid(predicts)

        outputs = {
            'predicts': predicts,
            'cls_feats': cls_feats,
            'label_feats': label_feats
        }
        return outputs
'''

class Transformer(nn.Module):

    def __init__(self, base_model, num_classes, method, promise_dim):
        super().__init__()
        self.base_model = base_model
        self.num_classes = num_classes
        self.method = method
        self.linear = nn.Linear(base_model.config.hidden_size, 300)
        self.pred_class = nn.Linear(211, self.num_classes)
        self.dropout = nn.Dropout(0.5)
        for param in base_model.parameters():
            param.requires_grad_(True)

        self.embedding_dim = base_model.config.hidden_size

        self.input_channel = 1  # for single embedding, input_channel = 1
        self.output_channel = 64   # number of kernels

        # 3 convolutional nets
        self.conv1 = nn.Conv2d(self.input_channel, self.output_channel, (1, self.embedding_dim), padding=(2, 0), groups=1)
        self.conv2 = nn.Conv2d(self.input_channel, self.output_channel, (2, self.embedding_dim), padding=(3, 0), groups=1)
        self.conv3 = nn.Conv2d(self.input_channel, self.output_channel, (3, self.embedding_dim), padding=(4, 0), groups=1)

    def conv_block(self, input, conv_layer):

        conv_out = F.relu(conv_layer(input))
        conv_out = torch.squeeze(conv_out,-1)
        max_out = F.max_pool1d(conv_out, conv_out.size()[2])

        return max_out

    def forward(self,promise, *args, **kwargs):
    #def forward(self, *args, **kwargs):

        raw_outputs = self.base_model(*args, **kwargs)
        #raw_outputs = self.base_model.generate(*args, **kwargs)
        #print("output is here2")
        #print(raw_outputs)
        hiddens = raw_outputs.last_hidden_state
        #print("output is here3")

        #cls_feats = torch.sum(hiddens, 1)  sum of all hidden
        #cls_feats = torch.mean(hiddens, 1)  #average of all hidden

        cls_feats = hiddens[:, 0, :]
        #print("hidden", hiddens.unsqueeze(1).size())
        x = [F.relu(self.conv1(hiddens.unsqueeze(1))).squeeze(3), F.relu(self.conv2(hiddens.unsqueeze(1))).squeeze(3), F.relu(self.conv3(hiddens.unsqueeze(1))).squeeze(3)]
        # max-over-time pooling; # (batch, channel_output) * ks
        x = [F.max_pool1d(i, i.size(2)).squeeze(2) for i in x]
        # concat results; (batch, channel_output * ks)
        cls_feats = torch.cat(x, 1)

        label_feats = None
        ####predicts = self.linear(self.dropout(cls_feats))
        ###predicts = torch.cat((predicts, promise), 1)
        cls_feats_cat = torch.cat((cls_feats, promise), 1)
        predicts = self.pred_class(self.dropout(cls_feats_cat))
        #print("cls_feats",predicts.size())
        predicts = torch.sigmoid(predicts)


        outputs = {
            'predicts': predicts,
            'cls_feats': cls_feats_cat,
            'label_feats': label_feats
        }
        return outputs

"""#main score"""

pip install transformers

pip install torchmetrics

import torch
from tqdm import tqdm
from transformers import logging, AutoTokenizer, AutoModel
from transformers import logging, AutoTokenizer, AutoModel
from torchmetrics import F1Score
from sklearn.metrics import accuracy_score
import numpy as np
from numpy import vstack
from torchmetrics.classification import BinaryF1Score
from torchmetrics import Accuracy

from sklearn.metrics import f1_score
from torchmetrics import ConfusionMatrix
from mlxtend.plotting import plot_confusion_matrix
from torchmetrics.classification import BinaryConfusionMatrix
import matplotlib.pyplot as plt

from sklearn.metrics import confusion_matrix, classification_report

def ppv(tn, fp, fn, tp):
  return tp / (tp + fp)

def tpr(tn, fp, fn, tp):
  return tp / (tp + fn)

def f1(tp, fn, fp, tn):
  p = ppv(tn, fp, fn, tp)
  r = tpr(tn, fp, fn, tp)

  return (2*p*r) / (p + r)

Result_PATH = '/content/drive/MyDrive/Proposed_BaseLine/CPDP_CL/finetune/Results_CPDP/{}/results/'.format(train_dataset)
Embed_PATH = '/content/drive/MyDrive/Proposed_BaseLine/CPDP_CL/finetune/Results_CPDP/{}/embed/'.format(train_dataset)
Model_PATH = '/content/drive/MyDrive/Proposed_BaseLine/CPDP_CL/finetune/Models_HC/'
Model_Last_PATH = '/content/drive/MyDrive/Proposed_BaseLine/CPDP_CL/finetune/Models_HC_Last/'
Model_Last_PATH ='/content/drive/MyDrive/Proposed_BaseLine/CPDP_CL/finetune/Models_HC_Last/'

if not os.path.exists(Result_PATH):
  os.mkdir('/content/drive/MyDrive/Proposed_BaseLine/CPDP_CL/finetune/Results_CPDP/{}/'.format(train_dataset))
  os.mkdir(Result_PATH)
  os.mkdir(Embed_PATH)
  #os.mkdir(Model_PATH)
  os.mkdir('/content/drive/MyDrive/Proposed_BaseLine/CPDP_CL/finetune/Results_CPDP/{}/results/prediction'.format(train_dataset))

#if not os.path.exists()



"""#MMD"""

class Instructor:

    def __init__(self, logger):
        self.logger = logger
        self.logger.info('> creating model {}'.format(model_name))
        if model_name == 'bert':
            self.tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
            base_model = AutoModel.from_pretrained('bert-base-uncased')
            #base_model = BertModel.from_pretrained("tsdae_model/0_Transformer")
        elif model_name == 'roberta':
            #self.tokenizer = AutoTokenizer.from_pretrained('roberta-base', add_prefix_space=True)
            #base_model = AutoModel.from_pretrained('roberta-base')

            self.tokenizer = AutoTokenizer.from_pretrained('microsoft/codebert-base', add_prefix_space=True)
            base_model= AutoModel.from_pretrained('microsoft/codebert-base')

            '''ckpt = "mrm8488/longformer-base-4096-finetuned-squadv2"
            self.tokenizer = LongformerTokenizer.from_pretrained(ckpt)
            base_model = LongformerModel.from_pretrained(ckpt)'''

        else:
            raise ValueError('unknown model')
        self.model = Transformer(base_model, num_classes, method, promise_dim)
        self.model.to(device)
        if device.type == 'cuda':
            self.logger.info('> cuda memory allocated: {}'.format(torch.cuda.memory_allocated(device.index)))
        self._print_args()

    def _print_args(self):
        self.logger.info('> training arguments:')
        #for arg in vars(self.args):
        #    self.logger.info(f">>> {arg}: {getattr(self.args, arg)}")

    def _train(self, dataloader, test_dataloader, criterion, optimizer):
        train_loss, n_correct, n_train = 0, 0, 0

        n=0
        preds, actuals= list(), list()

        self.model.train()
        #for inputs,promise, targets in tqdm(dataloader, disable=backend, ascii=' >='):
        for step, (trainbatch, testbatch) in enumerate(zip(dataloader, test_dataloader)):

            train_inputs = {k: v.to(device) for k, v in trainbatch[0].items()}
            train_promise = torch.tensor(trainbatch[1]).to(device)
            train_targets = trainbatch[2].to(device)
            train_outputs = self.model(train_promise.float(), **train_inputs)

            test_inputs = {k: v.to(device) for k, v in testbatch[0].items()}
            test_promise = torch.tensor(testbatch[1]).to(device)
            test_targets = testbatch[2].to(device)
            test_outputs = self.model(test_promise.float(), **test_inputs)

            '''inputs = {k: v.to(device) for k, v in inputs.items()}
            promise = torch.tensor(promise).to(device)
            targets = targets.to(device)
            outputs = self.model(promise.float(), **inputs)'''

            ############# loss ################

            loss = criterion(train_outputs, train_targets)

            #print(train_outputs['cls_feats'].size(), test_outputs['cls_feats'].size())

            #md_loss = mmd_loss(train_outputs['cls_feats'], test_outputs['cls_feats'],5)
            #md_loss =  mix_rbf_mmd2(train_outputs['cls_feats'], test_outputs['cls_feats'], [0.2, 10.2, 100.005, 5], biased=True)


            #print(train_outputs['cls_feats'].size(),test_outputs['cls_feats'].size())
            if test_outputs['cls_feats'].size(dim=0) > train_outputs['cls_feats'].size(dim=0):
              md_loss = mmd_loss_2(train_outputs['cls_feats'], test_outputs['cls_feats'][:train_outputs['cls_feats'].size(dim=0)])
            else:
              md_loss = mmd_loss_2(train_outputs['cls_feats'][:test_outputs['cls_feats'].size(dim=0)], test_outputs['cls_feats'])

            #Replaces pow(2.0) with abs() for L1 regularization
            l2_lambda = 0.001
            l2_norm = sum(p.pow(2.0).sum() for p in self.model.parameters())

            loss = loss + l2_lambda * l2_norm + md_loss

            torch.cuda.empty_cache()

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            torch.cuda.empty_cache()

            train_loss += loss.item() * train_targets .size(0)
            n_correct += (torch.argmax(train_outputs['predicts'], -1) == train_targets ).sum().item()
            n_train += train_targets .size(0)

            prediction=torch.argmax(train_outputs['predicts'], -1)
            #targ = torch.tensor(train_targets )
            #preds = torch.tensor(prediction)


            #confusion matrix
            metric_bin = BinaryConfusionMatrix().to(device)
            ##########print("\n")
            ###########print(metric_bin(prediction,train_targets ))

            n +=1


        return train_loss / n_train, n_correct / n_train

    def _test(self, dataloader, criterion):
        test_loss, n_correct, n_test = 0, 0, 0
        self.model.eval()
        n=0

        tru_lbl=[]
        pr_lbl=[]

        out=[]
        prd=[]

        with torch.no_grad():
            for inputs, promise, targets in tqdm(dataloader, disable=backend, ascii=' >='):
                inputs = {k: v.to(device) for k, v in inputs.items()}
                promise = torch.tensor(promise).to(device)
                targets = targets.to(device)
                outputs = self.model(promise.float(), **inputs)
                loss = criterion(outputs, targets)
                test_loss += loss.item() * targets.size(0)
                n_correct += (torch.argmax(outputs['predicts'], -1) == targets).sum().item()
                n_test += targets.size(0)

                n +=1

                prediction=torch.argmax(outputs['predicts'], -1)

                #confusion matrix
                metric_bin = BinaryConfusionMatrix().to(device)
                #######print("\n")
                #######print(metric_bin(prediction,targets))

                pr_lbl.extend(prediction.detach().cpu().numpy())
                tru_lbl.extend(targets.detach().cpu().numpy())

                out.extend(outputs['predicts'])
                prd.extend(targets)

        tn, fp, fn, tp = confusion_matrix(tru_lbl, pr_lbl).ravel()
        #f1_pos =  f1(tn, fp, fn, tp)
        #tp, fn, fp, tn = confusion_matrix(tru_lbl, pr_lbl).ravel()

        ####f1_neg= f1(tp, fn, fp, tn)

        f1_neg= f1(tn, fp, fn, tp)
        f1_pos= f1(tp, fn, fp, tn)

        #print("code is here")
        #loss = crtn(torch.tensor(out), torch.tensor(prd))
        print(classification_report(tru_lbl, pr_lbl))
        print(confusion_matrix(tru_lbl, pr_lbl))
        #Accuracy score
        #print("ACC: ",accuracy_score(pr_lbl,tru_lbl))
        #print("best score: ",accuracy_score(pr_lbl,tru_lbl))

        ####print("f1_pos", f1(tp, fn, fp, tn), f1_neg)
        print("f1_neg", f1(tn, fp, fn, tp), f1_neg)

        return loss, n_correct / n_test,f1_pos , f1_neg

    def run(self):

        '''train_dataloader, test_dataloader, valid_dataloader = load_data(dataset=dataset_name,
                                                      data_dir=data_dir,
                                                      tokenizer=self.tokenizer,
                                                      train_batch_size=train_batch_size,
                                                      test_batch_size=test_batch_size,
                                                      model_name=model_name,
                                                      method=method,
                                                      workers=0)'''

        train_dataloader, test_dataloader = load_data(train_dataset,test_dataset, data_dir,
                                                      self.tokenizer,
                                                      train_batch_size, test_batch_size,
                                                      model_name, method,
                                                      2)
        ######################################
        valid_dataloader = test_dataloader  ##
        ######################################


        _params = filter(lambda p: p.requires_grad, self.model.parameters())
        if method == 'ce':
            criterion = CELoss()
        elif method == 'scl':
            criterion = SupConLoss(alpha, temp)
        elif method == 'dualcl':
            criterion = DualLoss(alpha, temp)
        else:
            raise ValueError('unknown method')

        optimizer = torch.optim.AdamW(_params, lr=lr, weight_decay=decay)

        best_f1_p = 0
        best_f1_n = 0
        best_loss = float('inf')
        store_epo = 0

        for epoch in range(num_epoch):
            train_loss, train_acc = self._train(train_dataloader, test_dataloader, criterion, optimizer)
            #test_loss_t, test_acc_t, f1_pos_t = self._test(test_dataloader, criterion)
            test_loss, test_acc, f1_neg, f1_pos = self._test(valid_dataloader, criterion)

            if f1_pos > best_f1_p and f1_neg> 0.20 :  #f1_neg >= best_f1_n:

              #best_f1_n = f1_neg
              best_f1_p = f1_pos

              store_epo = epoch+1

              print("best F1-score", f1_pos)
              print("best epoch", store_epo)



              torch.save({'epoch': epoch,
                            'model_state_dict': self.model.state_dict(),
                            'optimizer_state_dict': optimizer.state_dict(),
                            'loss': test_loss
                            }, Model_PATH+'{}_SCL_LR_model_iter.pth'.format(dataset_name) )

            elif  round(f1_pos, 2) >= round(best_f1_p, 2) and round(f1_neg, 2) >= round(best_f1_n, 2) and f1_neg>20:

              best_f1_n = f1_neg
              best_f1_p = f1_pos

              store_epo = epoch+1

              print("best F1-score", f1_pos)
              print("best epoch", store_epo)



              torch.save({'epoch': epoch,
                            'model_state_dict': self.model.state_dict(),
                            'optimizer_state_dict': optimizer.state_dict(),
                            'loss': test_loss
                            }, Model_PATH+'{}_SCL_LR_model_iter_new.pth'.format(dataset_name) )


            self.logger.info('{}/{} - {:.2f}%'.format(epoch+1, num_epoch, 100*(epoch+1)/num_epoch))
            self.logger.info('[train] loss: {:.4f}, acc: {:.2f}'.format(train_loss, train_acc*100))
            self.logger.info('[test] loss: {:.4f}, acc: {:.2f}'.format(test_loss, test_acc*100))

        torch.save({'epoch': epoch,
                            'model_state_dict': self.model.state_dict(),
                            'optimizer_state_dict': optimizer.state_dict(),
                            'loss': test_loss
                            }, Model_Last_PATH +'{}_last_epch_SCL_LR_model_iter_new.pth'.format(dataset_name) )

        self.logger.info('best loss: {:.4f}, best acc: {:.2f}, store_epoch:{}'.format(best_loss, best_f1_p,store_epo))
        self.logger.info('log saved: {}'.format(log_name))

"""#MAIN FUNCTION"""

num_epoch=25

from sklearn.model_selection import train_test_split

ins = Instructor(logger)
ins.run()

torch.cuda.empty_cache()
torch.cuda.empty_cache()
torch.cuda.empty_cache()

#impact of loss on model performance xavier vs triplet loss

"""# Result Analysis"""

class_labels=["Clean","Bug"]

"""Accuracy Score"""

def accuracy(y_test, predictions):
  RF_accuracy = accuracy_score(y_true=y_test, y_pred= predictions)
  return RF_accuracy

"""Classification Report"""

def class_report(y_test, predictions):
  print(classification_report(y_true=y_test, y_pred=predictions,target_names=class_labels))

"""Confusion Matrix"""

from mlxtend.plotting import plot_confusion_matrix
def confusion_mat(y_test, predictions):
  ax=plot_confusion_matrix(conf_mat=confusion_matrix(y_test, predictions),
                        figsize=(10,5),
                        class_names=class_labels,
                        cmap=plt.cm.Greens)
  plt.title(label="Confusion Matrix")
  plt.show()
  tn, fp, fn, tp = confusion_matrix(y_test, predictions).ravel()
  return tn, fp, fn, tp

"""$Accuracy$ =  $\frac{TP + TN}{TP + TN + FP + FN}$"""

def accuracy(tn, fp, fn, tp):
  return (tp + tn) / (tp + tn + fp + fn)

"""$Recall$ = $Sensitivity$ = $True$ $Positive$ $Rate$ = $\frac{TP}{TP + FN}$"""

def tpr(tn, fp, fn, tp):
  return tp / (tp + fn)

"""$False$ $Negative$ $Rate$ = $\frac{FN}{TP + FN}$"""

def fnr(tn, fp, fn, tp):
  return fn / (tp + fn)

"""$Specificity$ = $True$ $Negative$ $Rate$ = $\frac{TN}{TN + FP}$"""

def tnr(tn, fp, fn, tp):
  return tn / (tn + fp)

"""$False$ $Positive$ $Rate$ = $\frac{FP}{TN + FP}$"""

def fpr(tn, fp, fn, tp):
  return fp / (tn + fp)

"""$Precision$ = $Positive$ $Predictive$ $Value$ = $\frac{TP}{TP + FP}$"""

def ppv(tn, fp, fn, tp):
  return tp / (tp + fp)

"""$Negative$ $Predictive$ $Value$ = $\frac{TN}{TN + FN}$"""

def npv(tn, fp, fn, tp):
  return tn / (tn + fn)

"""$Balanced$ $Accuracy$ = $\frac{(TPR + TNR)}{2}$"""

def balanced_accuracy(tn, fp, fn, tp):
  tprr = tpr(tn, fp, fn, tp)
  tnrr = tnr(tn, fp, fn, tp)
  return (tprr + tnrr) / 2

"""$F_1$ = $\frac{2*Precisicion*Recall}{Precision + Recall}$"""

def f1(tn, fp, fn, tp):
  p = ppv(tn, fp, fn, tp)
  r = tpr(tn, fp, fn, tp)

  return (2*p*r) / (p + r)

"""$Matthews$ $Correlation$ $Coefficient$ = $\frac{(TP * TN) - (FP * FN)}{\sqrt{(TP + FP) * (TP + FN) * (TN + FP) * (TN + FN)}}$"""

from math import sqrt

def mcc(tn, fp, fn, tp):
  top = (tp * tn) - (fp * fn)
  bot = (tp + fp) * (tp + fn) * (tn + fp) * (tn + fn)
  return top / sqrt(bot)

"""AUC"""

from sklearn import metrics
def auc(y_test, predictions):
  fpr, tpr, thresholds = metrics.roc_curve(y_test, predictions, pos_label=1)
  return metrics.auc(fpr, tpr)

"""#load saved optimized model"""

PATH_Model= Model_PATH

#dataset_name'/content/drive/MyDrive/Proposed_BaseLine/proposed_model/BERT_SCL_HC_LR/Models_HC/final best model/'

#tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
#base_model = AutoModel.from_pretrained('bert-base-uncased')

tokenizer = AutoTokenizer.from_pretrained('microsoft/codebert-base', add_prefix_space=True)
base_model= AutoModel.from_pretrained('microsoft/codebert-base')

from sklearn import manifold
import pandas as pd

def draw_tsne(input,label,img_name):

    tsne = manifold.TSNE(n_components=2, init='pca', random_state=501)
    X_tsne = tsne.fit_transform(input)
    np.save("X_tsne.npy", X_tsne)

    x_min, x_max = X_tsne.min(0), X_tsne.max(0)
    X_norm = (X_tsne - x_min) / (x_max - x_min)

    plt.figure(figsize=(8, 8))
    label_tmp=[]
    for i in range(X_norm.shape[0]):
        label_tmp.append(label[i])
    plt.scatter(X_norm[:, 0], X_norm[:, 1], marker = 'o', c = label_tmp, cmap = 'coolwarm')
    plt.xticks([])
    plt.yticks([])

    plt.savefig(Embed_PATH + img_name)
    #plt.show()
    plt.close('all')

#Result_PATH = '/content/drive/MyDrive/Proposed_BaseLine/proposed_model/Results_WP_CP/{}/results/'.format(train_dataset)
#Embed_PATH = '/content/drive/MyDrive/Proposed_BaseLine/proposed_model/Results_WP_CP/{}/embed/'.format(train_dataset)

test_embbb= 211

def predict_defective_files_in_releases(dataset_name, train_dataset, test_dataset, valid_dataset):

  model = Transformer(base_model, num_classes, method,promise_dim)
  #checkpoint = torch.load(PATH_Model+'{}_SCL_LR_model_iter.pth'.format(dataset_name))
  checkpoint = torch.load(Model_Last_PATH+'{}_last_epch_SCL_LR_model_iter_new.pth'.format(dataset_name))

  model.load_state_dict(checkpoint['model_state_dict'])
  model.to(device)

  train_dataloader, test_dataloader = load_data(train_dataset=train_dataset,
                                                test_dataset=test_dataset,
                                                      data_dir=data_dir,
                                                      tokenizer=tokenizer,
                                                      train_batch_size=train_batch_size,
                                                      test_batch_size=test_batch_size,
                                                      model_name=model_name,
                                                      method=method,
                                                      workers=0)
  criterion = SupConLoss(alpha, temp)
  _params = filter(lambda p: p.requires_grad, model.parameters())
  optimizer = torch.optim.AdamW(_params, lr=lr, weight_decay=decay)
  #####
  test_loss, n_correct, n_test = 0, 0, 0
  ###
  model.eval()
  n=0
  tru_lbl=[]
  pr_lbl=[]
  pr_prob=[]

  #draw TSE Embedding
  test_embeddings = torch.zeros((0, test_embbb), dtype=torch.float32)

  with torch.no_grad():
    for inputs, promise, targets in tqdm(test_dataloader, disable=backend, ascii=' >='):
      inputs = {k: v.to(device) for k, v in inputs.items()}
      promise = torch.tensor(promise).to(device)
      targets = targets.to(device)
      outputs = model(promise.float(), **inputs)
      loss = criterion(outputs, targets)
      test_loss += loss.item() * targets.size(0)
      n_correct += (torch.argmax(outputs['predicts'], -1) == targets).sum().item()
      n_test += targets.size(0)
      n +=1
      prediction=torch.argmax(outputs['predicts'],-1)
      pr_lbl.extend(prediction.detach().cpu().numpy())
      tru_lbl.extend(targets.detach().cpu().numpy())
      pr_prob.extend(torch.max(outputs['predicts'],1).values.detach().cpu().numpy())
      test_embeddings = torch.cat((test_embeddings, outputs['cls_feats'].detach().cpu()), 0)


  tn, fp, fn, tp = confusion_matrix(tru_lbl, pr_lbl).ravel()
  print(classification_report(tru_lbl, pr_lbl))
  print(confusion_matrix(tru_lbl, pr_lbl))

  path = '/content/drive/MyDrive/Proposed_BaseLine/CPDP_CL/finetune/Results_CPDP/Result_Proposed_SCL_LR.csv'
  if os.path.exists(path):
    df=pd.read_csv(path)
  else:
    # create an Empty DataFrame object
    df = pd.DataFrame(columns = ['Train Project', 'Valid Project', 'Test Project', 'True Positive',
                  'False Positive', 'True Negative', 'False Negative', 'F1-Score', 'Precision', 'Recall', 'MCC', 'AUC'])

  path = '/content/drive/MyDrive/Proposed_BaseLine/CPDP_CL/codet5/Results_CPDP/Result_Proposed_SCL_LR.csv'
  if os.path.exists(path):
    df=pd.read_csv(path)
  else:
    # create an Empty DataFrame object
    df = pd.DataFrame(columns = ['Train Project', 'Valid Project', 'Test Project', 'True Positive',
                  'False Positive', 'True Negative', 'False Negative', 'F1-Score', 'Precision', 'Recall', 'MCC', 'AUC'])


  # Create a dictionary for the new row
  new_row = {'Train Project':train_dataset,
                'Valid Project':valid_dataset,
                'Test Project':test_dataset,
                'True Positive':tp,
                'False Positive':fp,
                'True Negative':tn,
                'False Negative':fn,
                'Loss': test_loss,
                'F1-Score':f1(tp, fn, fp, tn),
                'Precision':ppv(tp, fn, fp, tn),
                'Recall':tpr(tp, fn, fp, tn),
                'MCC':mcc(tp, fn, fp, tn),
                'AUC':auc(tru_lbl, pr_lbl)}

  # Append the new row to the DataFrame
  df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)

  df.to_csv(path, index=False)
  df = pd.DataFrame(list(zip(tru_lbl, pr_prob, np.round(np.array(pr_lbl)))),
               columns =['file_label', 'prediction-prob','prediction-label'])
  df.to_csv(Result_PATH+'/prediction/Test_{}_{}_{}_True_Predicted_Labels.csv'.format(train_dataset, valid_dataset, test_dataset), index=False)


  #embed
  test_embeddings = np.array(test_embeddings)
  draw_tsne(test_embeddings,tru_lbl,'{}_{}_{}_embedding.jpg'.format(train_dataset, valid_dataset, test_dataset))

  print('finished',train_dataset, test_dataset)

predict_defective_files_in_releases(dataset_name, train_dataset,test_dataset, test_dataset)
torch.cuda.empty_cache()

predict_defective_files_in_releases(dataset_name, train_dataset,train_dataset, train_dataset)
torch.cuda.empty_cache()

torch.cuda.empty_cache()